### ISSUE TITLE
[provider lease-shell] akash provider may not select the correct pod

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1480] opened 2021-12-21 11:46 UTC
Akash provider should update its reference to the deployment when it got its name changed for whatever reason.
Or, it should create the deployment in a way that it would terminate the deployment instead of recreating it with the new name?

**Reproducer:**

1. create a deployment;
2. `akash provider lease-shell` is working;
3. create a file larger than requested storage set in the deployment manifest;
4. `akash provider lease-shell` stops working;

```
$ akash provider lease-shell --tty --stdin --from default --dseq 3944427 --provider akash1nxq8gmsw2vlz3m68qvyvcf3kh6q269ajvqw6y0 -- echoserver sh
Error: lease shell failed: remote command execute error: service with that name is not running: the service has failed
```

I think the reason why this happens is because `echoserver-5b5556d669-jbfhn` gets replaced by `echoserver-5b5556d669-ldsc4` and akash provider does not update the handle to the new pod.

```
root@akash-master-01:~# kubectl get pods -A -o wide |grep echos
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   echoserver-5b5556d669-jbfhn                          0/1     ContainerStatusUnknown   1              9m53s   10.233.109.67    akash-worker-04.nixaid.com   <none>           <none>
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   echoserver-5b5556d669-ldsc4                          1/1     Running                  0              2m1s    10.233.109.68    akash-worker-04.nixaid.com   <none>           <none>

root@akash-master-01:~# kubectl get events --sort-by='.metadata.creationTimestamp' -A | tail -10
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   9m17s       Normal    Pulled                    pod/echoserver-5b5556d669-jbfhn                         Container image "gcr.io/google_containers/echoserver:1.10" already present on machine
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   9m16s       Normal    Started                   pod/echoserver-5b5556d669-jbfhn                         Started container echoserver
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   9m17s       Normal    Created                   pod/echoserver-5b5556d669-jbfhn                         Created container echoserver
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   87s         Normal    Killing                   pod/echoserver-5b5556d669-jbfhn                         Stopping container echoserver
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   87s         Warning   Evicted                   pod/echoserver-5b5556d669-jbfhn                         Container echoserver exceeded its local ephemeral storage limit "134217728".
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   87s         Normal    SuccessfulCreate          replicaset/echoserver-5b5556d669                        Created pod: echoserver-5b5556d669-ldsc4
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   86s         Normal    Scheduled                 pod/echoserver-5b5556d669-ldsc4                         Successfully assigned tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq/echoserver-5b5556d669-ldsc4 to akash-worker-04.nixaid.com
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   85s         Normal    Pulled                    pod/echoserver-5b5556d669-ldsc4                         Container image "gcr.io/google_containers/echoserver:1.10" already present on machine
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   84s         Normal    Created                   pod/echoserver-5b5556d669-ldsc4                         Created container echoserver
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   84s         Normal    Started                   pod/echoserver-5b5556d669-ldsc4                         Started container echoserver


root@akash-master-01:~# kubectl get pods -A |grep echos
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   echoserver-5b5556d669-jbfhn                          0/1     ContainerStatusUnknown   1              8m5s
tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq   echoserver-5b5556d669-ldsc4                          1/1     Running                  0              13s
root@akash-master-01:~# kubectl -n tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq describe pod echoserver-5b5556d669-jbfhn
...
...
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  8m16s  default-scheduler  Successfully assigned tb1ruhqstd7u1qvpe94dqv6e4n92ffiqd3pgulv5vrroq/echoserver-5b5556d669-jbfhn to akash-worker-04.nixaid.com
  Normal   Pulled     8m15s  kubelet            Container image "gcr.io/google_containers/echoserver:1.10" already present on machine
  Normal   Created    8m15s  kubelet            Created container echoserver
  Normal   Started    8m14s  kubelet            Started container echoserver
  Warning  Evicted    25s    kubelet            Container echoserver exceeded its local ephemeral storage limit "134217728".
  Normal   Killing    25s    kubelet            Stopping container echoserver
```

cc @boz @dmikey

**Comment by hydrogen18** [comment] 2021-12-21 21:22
Hi Andy, thanks for the thorough investigation! This is an interesting corner case. I will do some more investigation and identify a fix for this. It should be pretty easy.

**Comment by hydrogen18** [comment] 2022-02-10 20:49
Reproducing this was easy. Just use `akash provider lease-shell` to run a shell then run ` dd if=/dev/zero of=/x` inside the shell. The pod has the following events

```
│   Normal   Scheduled  104s  default-scheduler            Successfully assigned sg4o8bsmkkvb9umbhu2c3bgmsv94r52u92k0p3vbc7gjm/web-bd9d4dd97-ljs4d to kube-control-plane                        │
│   Normal   Pulled     103s  kubelet, kube-control-plane  Container image "quay.io/ovrclk/demo-app" already present on machine                                                                 │
│   Normal   Created    103s  kubelet, kube-control-plane  Created container web                                                                                                                │
│   Normal   Started    103s  kubelet, kube-control-plane  Started container web                                                                                                                │
│   Warning  Evicted    53s   kubelet, kube-control-plane  Container web exceeded its local ephemeral storage limit "134217728".                                                                │
│   Normal   Killing    53s   kubelet, kube-control-plane  Stopping container web             
```

The container dies. The pod condition becomes `Ready = false`. I'm going to update the code to check for this since we should not be trying to invoke a shell on a pod that isn't actually ready. This will return an error message to the client that is more informative.

**Closed** 2022-02-22 17:59 UTC
