### ISSUE TITLE
Inventory not accurate

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1002] opened 2020-12-16 10:13 UTC
It is bidding on and attempting to run workloads that cannot start.  One example from testnet:

It was killing workloads with events like this:

`kubectl get events -Aw`:
```
default                                         10m         Warning   SystemOOM          node/node1                     System OOM encountered, victim process: node, pid: 907115
```

While [pstats.sh](https://github.com/ovrclk/testnet-utils/blob/master/pstats.sh) showed this (plenty of memory available):

```
provider   num  num-p  cpu   cpu-a   cpu-p  mem      mem-a    mem-p  fs    fs-a     fs-p
provider1  1    0      1     7.101   0      1        24.8354  0      0.5   196.253  0
provider2  0    0      0     15.29   0      0        24.0169  0      0     394.302  0
provider3  2    0      15.2  6.923   0      11.2539  24.2524  0      35.5  196.253  0
provider4  0    0      0     15.272  0      0        23.9496  0      0     394.302  0
provider5  2    0      1.6   6.952   0      1.5      27.775   0      1     196.253  0
```

`kubectl top nodes`:

```
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
node1   875m         11%    6603Mi          21%
```

`kubectl top pods -A`:

```
NAMESPACE                                       NAME                                          CPU(cores)   MEMORY(bytes)   
7adgilh3phbo80ha387b0k6m84tkspteb7jmt97s576kg   api-f74f8fb74-8ksrz                           44m          141Mi           
7adgilh3phbo80ha387b0k6m84tkspteb7jmt97s576kg   mongo-54b565d7dd-rqhkv                        298m         126Mi           
akash-services                                  akash-provider-7786b5498f-hb5sh               10m          186Mi           
cert-manager                                    cert-manager-cainjector-fc6c787db-db9hw       4m           26Mi            
cert-manager                                    cert-manager-d994d94d7-4vgz9                  7m           19Mi            
cert-manager                                    cert-manager-webhook-845d9df8bf-fgtzr         4m           9Mi             
ingress-nginx                                   ingress-nginx-controller-d47nm                6m           155Mi           
j68n3i7vd9qu8ipa8cgo8qr9vd083qvor3jlsb3hhe1hi   redis-5f47b98f4f-755hp                        2m           2Mi             
j68n3i7vd9qu8ipa8cgo8qr9vd083qvor3jlsb3hhe1hi   web-7755dc7dd6-k9sl9                          0m           44Mi            
kube-system                                     calico-kube-controllers-7ccb6f74f9-xpz9c      3m           16Mi            
kube-system                                     calico-node-ffqmr                             52m          42Mi            
kube-system                                     coredns-84646c885d-8r9v5                      5m           10Mi            
kube-system                                     dns-autoscaler-7dd4b45894-8txp8               1m           7Mi             
kube-system                                     kube-apiserver-node1                          105m         398Mi           
kube-system                                     kube-controller-manager-node1                 27m          57Mi            
kube-system                                     kube-proxy-9ssdg                              12m          25Mi            
kube-system                                     kube-scheduler-node1                          7m           20Mi            
kube-system                                     kubernetes-dashboard-dfb67d98c-pttkn          2m           11Mi            
kube-system                                     kubernetes-metrics-scraper-54df648466-tzscc   1m           7Mi             
kube-system                                     metrics-server-7c5f68c54d-xhjd2               4m           22Mi            
kube-system                                     nodelocaldns-tvcq8                            10m          19Mi            
logdna-agent                                    logdna-agent-t5p74                            13m          21Mi            
```

**Comment by hydrogen18** [comment] 2020-12-16 17:45
While working on this I kept getting my K8S cluster stuck with loads of pods in "Pending". The provider eventually kills them. "Pending" means the cluster is ready to run my containers but has no place for them. 

This is confirmed by this message.

```
78n2dlheonpq7188530682d5ghk96q4bvfre0jnn75kb8   0s          Warning   FailedScheduling          pod/web-855cd69b9d-ck65v                                 0/3 nodes are available: 3 Insufficient cpu.
```

This is the code that computes available CPU in akash: https://github.com/ovrclk/akash/blob/55df3ff25ea673b0a72b97b91ad20f312b179d9e/provider/cluster/kube/client.go#L426

This is computed as `allocatable - usage`. Using this value to determine if we can deploy a pod doesn't make sense at all, the metrics server reports _usage_ of CPU. Unless all pods were always running 100% CPU there is no circumstance where `usage  == allocated`.

I'm going to fix this before moving onto the other problem.

**Comment by hydrogen18** [comment] 2020-12-16 22:18
I've continued to do some more testing around this. What I did was change the inventory calculation code to look at the nodes to get the allocatable capacity and the pods to get the allocated capacity. The metrics service is not used. Calculating the available is just `allocatable - allocated`. This seems to work just fine. The current frequency on this calculation logic is 5 seconds, I'm not sure why we are polling this so aggressively. It doesn't seem necessary.

After this code change I get the expected behavior when I try and spinup a large number of deployments using my provider. The provider bids on deployments until it no longer has any available resources in the cluster. No deployments get stuck in "Pending" in kubernetes due to a lack of resources.


![inventory_cpu](https://user-images.githubusercontent.com/130230/102413088-0b3dd280-3fba-11eb-8609-418a8f5e3c4c.png)


In reference to seeing OOM messages, The simplest explanation is that someone was deploying pods that had application that consume more memory than the limits they specified in the SDL. This always happens, regardless of available memory on the provider.

For example, if I do this in a container
```
cat /dev/zero > /dev/shm/foobar
```

I get this immediately in the kubernetes events

```
default                                         0s          Warning   SystemOOM                node/k8s-3                          System OOM encountered, victim process: cat, pid: 233818
```

I haven't found any other issues at present with the inventory code. I'm going to extend the scripts I've been using to create deployments to just endless open/close deployments to see if that gets the provider stuck in some bad state.

**Comment by boz** [comment] 2020-12-16 22:41
awesome!

it was using usage so that we could over-commit, but that was probably in conflict with the limits we put on the pods.

that explanation makes sense for the OOM.  we were also seeing similar out of cpu events, but I'll have to find my logs for that- maybe there's a different explanation.

**Comment by boz** [comment] 2020-12-17 07:39
We'll probably want to be able to tune over-commit sooner rather than later, but for now not over-committing at all is fine, especially since it's not working.

FWIW I thought that by not populating `Resources.Requests` that we'd be allowing over-commit.  Maybe they default `Resources.Requests` to `Resources.Limits` if it not populated now tho?

https://github.com/ovrclk/akash/blob/2a878164dff1e9b855ea782c60abb51f32660e13/provider/cluster/kube/builder.go#L249-L253

**Comment by hydrogen18** [comment] 2020-12-17 18:55
It looks like in the absence of requests being specified, the limits get copied over into requests when Kubernetes creates a pod.

The bottom line here is a deployment made by the provider

```
  Namespace                                      Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                                      ----                                       ------------  ----------  ---------------  -------------  ---
  cert-manager                                   cert-manager-cainjector-fc6c787db-hzt5x    0 (0%)        0 (0%)      0 (0%)           0 (0%)         12m
  cert-manager                                   cert-manager-webhook-845d9df8bf-kfz8q      0 (0%)        0 (0%)      0 (0%)           0 (0%)         12m
  ingress-nginx                                  ingress-nginx-controller-jr5q9             0 (0%)        0 (0%)      0 (0%)           0 (0%)         13m
  kube-system                                    coredns-84646c885d-ddh9m                   100m (11%)    0 (0%)      70Mi (4%)        170Mi (10%)    12m
  kube-system                                    dns-autoscaler-7dd4b45894-6cwk2            20m (2%)      0 (0%)      10Mi (0%)        0 (0%)         12m
  kube-system                                    kube-flannel-9wgpv                         150m (16%)    300m (33%)  64M (3%)         500M (29%)     13m
  kube-system                                    kube-proxy-5drhn                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         13m
  kube-system                                    nginx-proxy-k8s-2                          25m (2%)      0 (0%)      32M (1%)         0 (0%)         13m
  kube-system                                    nodelocaldns-bd65m                         100m (11%)    0 (0%)      70Mi (4%)        170Mi (10%)    12m
  q06t6net9eiac8aqm2s7s3mnlpmnet2isrrj37iki8ccm  web-67dfc54d7b-7x65h                       10m (1%)      10m (1%)    16777216 (0%)    16777216 (0%)  8m5s
```

The documentation here seems to indicate as such in a note on this page: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits . 

It doesn't say anything about ephemeral storage. Maybe we should make CPU overcommit a selectable feature on the provider? Over commit on storage / memory is a bit of a different problem.

I ran the same test again, adding and removing the deployments over and over again. My results from that aren't isn't conclusive yet.

There are two other places that I found where we don't handle deployments very well

https://github.com/ovrclk/akash/blob/master/provider/cluster/manager.go#L125

In this case if the deployment fails we log it and just keep going like it never happened. On the other hand, the monitor will stop the deployment _eventually_ but we really should be killing it immediately. Also we somehow need to give the owner the ability to see what happened.

The second case is here 

https://github.com/ovrclk/akash/blob/master/provider/cluster/manager.go#L157

This assigns `runch` so the code above receives any error. It does the same thing, just logging it and moving on. This is bad because if the teardown request failed then we basically can presume that the pod is still running in kubernetes. This would happen in the simplest of cases like a request timeout. If this happens enough then we'd eventually have no available resources. I'm going to change this to retry the request for a long period of time then log some sort of critical error because honestly at this point the provider has a serious problem. I'd rather tie up a goroutine, then potentially leak pods in Kubernetes.

**Comment by hydrogen18** [comment] 2020-12-17 21:29
I've ran my script to open / close deployments for an extended period of time now and I got this:

![inventory_cpu](https://user-images.githubusercontent.com/130230/102545891-7e0f8200-407c-11eb-9208-2f328c6ce55e.png)

Once all leases are closed, reservations goes back to zero and inventory goes back to the previous maximum.

This leads me to conclude there is no trivial issue with deployments being open & closed leading to an invalid state in our inventory code. I'm looking into other stuff now.

**Comment by hydrogen18** [comment] 2020-12-17 22:38
I opened #1007 to track some other problems I found in the log of the providers.

I did go ahead and confirm using LogDNA that some deployments were getting killed off by the monitor

This is from provider 4
```
Dec 10 11:33:34 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-10|17:33:34.628] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1yhfrk7jd98dxgfk6uwqfwkqutrxnexqatcxn9p/189311/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 10 11:38:10 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-10|17:38:10.672] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1yhfrk7jd98dxgfk6uwqfwkqutrxnexqatcxn9p/189357/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 01:27:51 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-11|07:27:51.845] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash10090ezxh44wwd4m5h24ddh8d54njf0yegdv4vw/198345/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 10:16:44 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-11|16:16:44.052] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1kfd3adu7sgcu2vxd3ucc3pehmrautp25kxenn5/204187/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 13:14:26 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-11|19:14:26.601] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash19uwxt0ln3p9fenpdwtsm5rlmqsekc3g9ym6xqz/206109/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 16:11:43 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-11|22:11:43.839] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1kfd3adu7sgcu2vxd3ucc3pehmrautp25kxenn5/208038/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 18:57:40 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|00:57:40.126] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash12wku5yef67c48lcenlj5m57t4fy0lsgjd70wcd/209819/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 11 23:07:33 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|05:07:33.025] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/212592/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 12 00:04:25 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|06:04:25.071] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/213214/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 12 00:14:05 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|06:14:05.394] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/213320/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 12 01:12:45 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|07:12:45.044] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/213957/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 12 01:35:52 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|07:35:52.546] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/214209/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 12 01:55:27 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-12|07:55:27.789] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash1m9ajhy4y9qlmdefy85r36q7k0x2ykz0jlht4wp/214416/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
Dec 14 01:23:39 akash-provider-f4949b664-jqpm8 akash-provider E[2020-12-14|07:23:39.919] deployment failed.  closing lease.           module=provider-cluster cmp=service cmp=deployment-manager lease=akash18vk3qc5fv5kt4wyazq3ejhjap7pqudqth2ll8k/245507/1/1/akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl manifest-group=westcoast cmp=deployment-monitor
```

However, there is no way I can think of to prove that this was due to pods stuck in the "pending" state although it does seem likely.

**Comment by boz** [comment] 2020-12-18 03:16
Great sleuthing

> It looks like in the absence of requests being specified, the limits get copied over into requests when Kubernetes creates a pod.
> 

Yep, looks like that's what was happening.

> It doesn't say anything about ephemeral storage. Maybe we should make CPU overcommit a selectable feature on the provider? Over commit on storage / memory is a bit of a different problem.
> 

I think that we should over-commit tune-able on all of them:

|flag|default|
|---|---|
|`--overcommit-pct-mem`|50|
|`--overcommit-pct-cpu`|50|
|`--overcommit-pct-ephemeral-storage`|25|

or something.

> 
> There are two other places that I found where we don't handle deployments very well
> 
> https://github.com/ovrclk/akash/blob/master/provider/cluster/manager.go#L125
> 
> In this case if the deployment fails we log it and just keep going like it never happened. On the other hand, the monitor will stop the deployment _eventually_ but we really should be killing it immediately. Also we somehow need to give the owner the ability to see what happened.
> 

Oof that's a tough one.  Have to think about it a bit.

> The second case is here
> 
> https://github.com/ovrclk/akash/blob/master/provider/cluster/manager.go#L157
> 
> This assigns `runch` so the code above receives any error. It does the same thing, just logging it and moving on. This is bad because if the teardown request failed then we basically can presume that the pod is still running in kubernetes. This would happen in the simplest of cases like a request timeout. If this happens enough then we'd eventually have no available resources. I'm going to change this to retry the request for a long period of time then log some sort of critical error because honestly at this point the provider has a serious problem. I'd rather tie up a goroutine, then potentially leak pods in Kubernetes.

I think you're right that we should retry, I also think that we should have some kind of reaper that checks for running namespaces that are for leases that are no longer active.  Kind of a catch-all for anything that falls through the cracks.

If the reaper finds a namespace for a lease that is closed:

1. give the normal process some time to close the ns (configurable, ~10 seconds)
2. if after some grace period the ns is still around, log **very loudly** and delete the namespace.

The reaper could be a totally separate process/container and wouldn't actually need chain private keys or anything.

**Comment by hydrogen18** [comment] 2020-12-18 13:54
The reaper would still need to talk to the provider to get a list of active leases, wouldn't it? Or is there some other way it could get that information.

**Comment by boz** [comment] 2020-12-18 16:23
> The reaper would still need to talk to the provider to get a list of active leases, wouldn't it? Or is there some other way it could get that information.

In #1009 I add `LeaseID` fields to the namespace labels, this thing can go through and check that each is active periodically by querying the chain.  It could potentially be a lot of querying, tho.

It _could_ be done in a shell script, but it might be ugly:

* `kubectl get ns --label akash.network/namespace` to get the namespaces (might want a more explicit label to mark them as namespaces for leases)
* `akash query market lease get` to get the lease status.

However it's done, we need something out-of-band that is a backstop to leaking workloads.

**Comment by hydrogen18** [comment] 2020-12-19 00:57
OK, After some refactoring I've got it changed so that we can have provider over committing resources based on command line switches, for example

```
Non-terminated Pods:                             (17 in total)
  Namespace                                      Name                                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                                      ----                                           ------------  ----------  ---------------  -------------  ---
  8ps5k205fjnb2qtmh1ukd25q115cuil5paputkgqc9sbc  web-577c595df-h8j69                            27m (3%)      80m (8%)    23068672 (1%)    23068672 (1%)  3s
  8u6lcjco8q1ptenp7emlbo3stdkelcr0d639h2geep5so  web-69766f58c6-tmvd2                           17m (1%)      50m (5%)    52428800 (3%)    52428800 (3%)  23s
  bighu26f4uefce7dgb9rpai4fckh864iv6p6ebmba2tta  web-6bf9ff9567-k4q78                           7m (0%)       20m (2%)    40894464 (2%)    40894464 (2%)  25s
```

These pods are spunup with requests set lower than limits (in this example CPU was used) so that it is over committed. After I add some test coverage around this functionality I'll push it up in a PR.

For the "reaper" I think I will just make another issue since it's a separate concern for now.

**Comment by boz** [comment] 2020-12-21 05:14
I forgot to mention that there is ovrclk/operations#40 to track the reaper.  feel free to close/edit/comment there.

**Comment by boz** [comment] 2020-12-21 05:17
> OK, After some refactoring I've got it changed so that we can have provider over committing resources based on command line switches, for example

AWESOME!

> 
> For the "reaper" I think I will just make another issue since it's a separate concern for now.

We have ovrclk/operations#40, tho I acknowledge that it's not clear where the best place to start actually implementing these things is.  We might want to start an open-source repository `akash-provider-ops` for these kinds of tools?  It'd be great to have it open so we can have the community contribute.  Not 100% sure what to do here tho.

**Closed** 2020-12-31 16:36 UTC
