### ISSUE TITLE
Investigate possible bid engine provider failures

### ISSUE THREAD

**Issue by akash-mm** [ovrclk/akash#1615] opened 2022-06-13 16:45 UTC
short term fix is to restart the nodes

for this story ldetermine if it's something like a deadlock? no avail inventory?

**Comment by tidrolpolelsef** [comment] 2022-06-21 14:48
is this a dupe of #1613 ?

**Comment by akash-mm** [comment] 2022-06-21 15:26
yes, good catch

**Closed** 2022-06-21 15:26 UTC
