### ISSUE TITLE
Sending provider manifest fails sporadically with 500 error

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#1673] opened 2022-07-19 21:25 UTC
Sending provider manifest fails sporadically with 500 error

```sh
akash tx deployment update --dseq 20241338 --from deploy -y .akash/cache/sdl.1658254820.yml
```
Returns (success):
```sh
{"height":"6814794","txhash":"4A725260FD70496FC0AAD2A7ECE9BF2B7986E530B68181FB57845D3F25871271","codespace":"","code":0,"data":"0A2F0A2D2F616B6173682E6465706C6F796D656E742E763162657461322E4D73675570646174654465706C6F796D656E74","raw_log":"[{\"events\":[{\"type\":\"akash.v1\",\"attributes\":[{\"key\":\"module\",\"value\":\"deployment\"},{\"key\":\"action\",\"value\":\"deployment-updated\"},{\"key\":\"version\",\"value\":\"3a197efe14e8e054de1e0c19b1099af16688482ff7c48829ed73099acf0e4741\"},{\"key\":\"owner\",\"value\":\"akash1w2tutrw8txcuw9nlcrqjnnvs85ah32z37cx7w4\"},{\"key\":\"dseq\",\"value\":\"20241338\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/akash.deployment.v1beta2.MsgUpdateDeployment\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"akash.v1","attributes":[{"key":"module","value":"deployment"},{"key":"action","value":"deployment-updated"},{"key":"version","value":"3a197efe14e8e054de1e0c19b1099af16688482ff7c48829ed73099acf0e4741"},{"key":"owner","value":"akash1w2tutrw8txcuw9nlcrqjnnvs85ah32z37cx7w4"},{"key":"dseq","value":"20241338"}]},{"type":"message","attributes":[{"key":"action","value":"/akash.deployment.v1beta2.MsgUpdateDeployment"}]}]}],"info":"","gas_wanted":"64897","gas_used":"62487","tx":null,"timestamp":"","events":[{"type":"coin_spent","attributes":[{"key":"c3BlbmRlcg==","value":"YWthc2gxdzJ0dXRydzh0eGN1dzlubGNycWpubnZzODVhaDMyejM3Y3g3dzQ=","index":true},{"key":"YW1vdW50","value":"MTYyM3Vha3Q=","index":true}]},{"type":"coin_received","attributes":[{"key":"cmVjZWl2ZXI=","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"YW1vdW50","value":"MTYyM3Vha3Q=","index":true}]},{"type":"transfer","attributes":[{"key":"cmVjaXBpZW50","value":"YWthc2gxN3hwZnZha20yYW1nOTYyeWxzNmY4NHoza2VsbDhjNWxhenc4ajg=","index":true},{"key":"c2VuZGVy","value":"YWthc2gxdzJ0dXRydzh0eGN1dzlubGNycWpubnZzODVhaDMyejM3Y3g3dzQ=","index":true},{"key":"YW1vdW50","value":"MTYyM3Vha3Q=","index":true}]},{"type":"message","attributes":[{"key":"c2VuZGVy","value":"YWthc2gxdzJ0dXRydzh0eGN1dzlubGNycWpubnZzODVhaDMyejM3Y3g3dzQ=","index":true}]},{"type":"tx","attributes":[{"key":"ZmVl","value":"MTYyM3Vha3Q=","index":true}]},{"type":"tx","attributes":[{"key":"YWNjX3NlcQ==","value":"YWthc2gxdzJ0dXRydzh0eGN1dzlubGNycWpubnZzODVhaDMyejM3Y3g3dzQvMjQ=","index":true}]},{"type":"tx","attributes":[{"key":"c2lnbmF0dXJl","value":"bEVkUGdRK2tETlVZdVpMemdqOW1hSkRiQ3VheEJWZ2hBeUY3RGxQdEtmMXRlVlBoamdTZjU2dXZSZWpFNmhWelJtYnRHbzZXUGNWa0VBQkZ5V2VnZnc9PQ==","index":true}]},{"type":"message","attributes":[{"key":"YWN0aW9u","value":"L2FrYXNoLmRlcGxveW1lbnQudjFiZXRhMi5Nc2dVcGRhdGVEZXBsb3ltZW50","index":true}]},{"type":"akash.v1","attributes":[{"key":"bW9kdWxl","value":"ZGVwbG95bWVudA==","index":true},{"key":"YWN0aW9u","value":"ZGVwbG95bWVudC11cGRhdGVk","index":true},{"key":"dmVyc2lvbg==","value":"M2ExOTdlZmUxNGU4ZTA1NGRlMWUwYzE5YjEwOTlhZjE2Njg4NDgyZmY3YzQ4ODI5ZWQ3MzA5OWFjZjBlNDc0MQ==","index":true},{"key":"b3duZXI=","value":"YWthc2gxdzJ0dXRydzh0eGN1dzlubGNycWpubnZzODVhaDMyejM3Y3g3dzQ=","index":true},{"key":"ZHNlcQ==","value":"MjAyNDEzMzg=","index":true}]}]}
```

Uploading Manifest

```sh
akash provider send-manifest --provider akash1qk9dg3kr3jx6q5l2uf7g7mm8st2mr8ylfakepy --dseq 20241338 --from deploy .akash/cache/sdl.1658254820.yml
```

Fails:

```
provider: akash1qk9dg3kr3jx6q5l2uf7g7mm8st2mr8ylfakepy
	status:       FAIL
	error:        remote server returned 500
	errorMessage: manifest version validation failed
```

Try again:

```
akash provider send-manifest --provider akash1qk9dg3kr3jx6q5l2uf7g7mm8st2mr8ylfakepy --dseq 20241338 --from deploy .akash/cache/sdl.1658254820.yml
```

Success:

```
provider: akash1qk9dg3kr3jx6q5l2uf7g7mm8st2mr8ylfakepy
	status:       PASS
```

**Comment by andy108369** [comment] 2022-07-19 22:01
Looks like the RPC node, provider is using, wasn't fast enough to see the new manifest on the blockchain at the time you have sent it to the provider. 

How long did you wait between tx update & send-manifest ?

**Comment by gosuri** [comment] 2022-07-19 23:50
milliseconds, it is an [automated](https://github.com/gosuri/eve/blob/main/cmd/deploy.go#L67) deployment update, `send-manifest` done immediately after `update-deployment`

**Comment by andy108369** [comment] 2022-07-20 06:14
> milliseconds, it is an [automated](https://github.com/gosuri/eve/blob/main/cmd/deploy.go#L67) deployment update, `send-manifest` done immediately after `update-deployment`

yeah, so it needs to either wait for at least the next block, or better have the exponential backoff with retry mechanism (for `send-manifest`) in the client, i.e. so if it fails for the first time, wait for 2 seconds before next retry, then 4, 8, 16 and so forth up to a reasonable amount before giving up. I'd say 5 blocks X 6 seconds = 30 seconds should be reasonable.

and/or, maybe the same (the exponential backoff with retry) could be implemented in the akash client itself on `send-manifest` 🤷

**Comment by andy108369** [comment] 2022-08-09 14:37
I'll close it as the cause has been figured out.

Please open a feature request if you want to request a change to the way how CLI behaves.

**Closed by andy108369** 2022-08-09 14:37 UTC
