### ISSUE TITLE
HTTP 1MB upload limit

### ISSUE THREAD

**Issue by tombeynon** [ovrclk/akash#1300] opened 2021-07-03 15:21 UTC
Uploading a file larger than 1MB to an HTTP endpoint will return a `413 Request Entity Too Large` error. 1MB is the default `client_max_body_size` setting for Nginx so I expect this is a limit at the HTTP proxy.

Nginx config and default: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Error returned:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by guacamole** [comment] 2021-07-04 04:42
@tombeynon , we have been facing the same issue while uploading docker images to Skynet through Akash.
Usually, docker images are larger than 5 MBs for most projects and even larger for Nodejs, Ruby and Python based projects.

We're currently developing Open Registry on Akash and Skynet and this is the only challenge we've been facing to get it through.

**Comment by boz** [comment] 2021-07-04 05:20
Thanks all.  We can change this to something larger quite easily.  We'll look into it next week.

**Comment by jay-dee7** [comment] 2021-07-10 13:08
@boz would it be possible to also add support for setting a custom value for this in our deployment manifest?

**Comment by boz** [comment] 2021-07-10 22:44
> @boz would it be possible to also add support for setting a custom value for this in our deployment manifest?

It _should_ be possible with our current backend tooling.  If it is, it'd be a matter of adding support for it in the manifest and provider services.  It's a very reasonable feature request, we'll try to prioritize it.

**Comment by arno01** [comment] 2021-10-17 21:28
Looks like the right way to achieve this should be this [`expose.http_options.max_body_size`](https://github.com/ovrclk/akash/blob/6f68770b632ecf8265da98071634ae698a532750/_run/kube/deployment.yaml#L10-L11)

Changing `proxy-body-size` in the `ingress-nginx-controller` ConfigMap like [here](https://github.com/ovrclk/akash/blob/b0a53d101867846ae8c911b3d8f33376aa9263c0/_run/ingress-nginx.yaml#L38-L39) does not seem to help as that would only change the `upstream-default-backend`, you can verify by running this command on the provider:

```
# kubectl -n ingress-nginx exec $(kubectl -n ingress-nginx get pods -l app.kubernetes.io/component=controller -o jsonpath='{.items[0].metadata.name}') -- cat /etc/nginx/nginx.conf | grep -Ei 'proxy_upstream_name|client_max_body_size'
```

However, the [`expose.http_options.max_body_size`](https://github.com/ovrclk/akash/blob/6f68770b632ecf8265da98071634ae698a532750/_run/kube/deployment.yaml#L10-L11) isn't seem to be implemented on the akash provider side itself as it didn't change the ingress configuration. (**akash** `v0.14.1-rc0`).


```
# kubectl -n dsuaebrpld2tpjrtcl13cl5fptmiebns2aqjvleo1beti get ing -o yaml | grep -i body-size
      nginx.ingress.kubernetes.io/proxy-body-size: "104857600"
      nginx.ingress.kubernetes.io/proxy-body-size: "104857600"
      nginx.ingress.kubernetes.io/proxy-body-size: "104857600"
``

**Comment by tombeynon** [comment] 2021-10-18 17:15
That was to `akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7`, it is an older deployment actually. I'll test a fresh deployment now

**Comment by hydrogen18** [comment] 2021-10-20 21:55
Appreciate your patience with this, I did some more testing today. 

I created a deployment with my SDL I use for testing this

```

```

1 megabyte file POST works OK

**Comment by arno01** [comment] 2021-10-31 22:28
I've redeployed the whole thing (Akash Provider & Kubernetes) from scratch, using https://nixaid.com/deploy-akash-provider-with-kubeadm/ -- cannot reproduce this issue anymore.

I've used `gcr.io/google_containers/echoserver:1.10` image.

@hydrogen18 you might need to fix your image `hydrogen18/http_behavior_diagnostic:20210914b` as always returns **413** for anything >= 10MiB:

```
$ docker run -p 8080:8080 --rm -ti hydrogen18/http_behavior_diagnostic:20210914b
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)

2021-10-31 22:25:42,800 aiohttp.access  INFO     START 'POST' '/body-size'
2021-10-31 22:25:42,814 aiohttp.access  INFO     172.17.0.1 [31/Oct/2021:22:25:42 +0000] "POST /body-size HTTP/1.1" 200 217 "-" "curl/7.68.0"
2021-10-31 22:25:45,344 aiohttp.access  INFO     START 'POST' '/body-size'
2021-10-31 22:25:45,356 aiohttp.access  INFO     172.17.0.1 [31/Oct/2021:22:25:45 +0000] "POST /body-size HTTP/1.1" 413 276 "-" "curl/7.68.0"
```

```
$ dd if=/dev/urandom of=testfile bs=1M count=9
9+0 records in
9+0 records out
9437184 bytes (9.4 MB, 9.0 MiB) copied, 0.0396766 s, 238 MB/s
$ curl -s -X POST localhost:8080/body-size -T testfile ; echo
request body size is 9437184 bytes

$ dd if=/dev/urandom of=testfile bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0442269 s, 237 MB/s
$ curl -s -X POST localhost:8080/body-size -T testfile ; echo
Maximum request body size 10485760.0 exceeded, actual body size 10485760
```

**Comment by guacamole** [comment] 2021-11-29 13:44
Hey Guys, 
any update on this issue ?
We're really waiting to use this feature

**Comment by hydrogen18** [comment] 2021-11-29 13:47
@arno01 said he cannot reproduce the issue any longer, so I'm closing this

**Closed by hydrogen18** 2021-11-29 13:47 UTC
Labels: kind/feature
