### ISSUE TITLE
state improvements

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#25] opened 2018-02-20 20:15 UTC
`state/{state,db}.go` store needs some improvements:

 * clone-able so that we can have a copy of the state running for `CheckTx` calls.
 * query at height: so that we can get older versions of objects for `Query()`.

query height should be handled in `app/app.go` so that a `state.State` is passed passed down to sub applications in the `Query()` call.

**Comment by nalesandro** [comment] 2018-03-19 18:11
Dupe of #67

**Closed by nalesandro** 2018-03-19 18:11 UTC
Labels: enhancement
