### ISSUE TITLE
Malformated HTTP response

### ISSUE THREAD

**Issue by camzilla1050** [ovrclk/akash#1689] opened 2022-09-11 17:36 UTC
Hello
After install node cli-build, i start service akash-node it seems ok

but command 
![Capture d’écran du 2022-09-11 19-34-18](https://user-images.githubusercontent.com/10384623/189541253-258e035a-05e2-4e84-9f9b-bbf891e33f73.png)

`akash status` returns
Error: post failed: Post "http://localhost:26657": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\""

**Comment by andy108369** [comment] 2022-09-11 19:40
Hi,

does `curl http://localhost:26657/status` return anything?

and what akash client version you have? (`akash version`)

**Comment by camzilla1050** [comment] 2022-09-11 20:27
hello, doing  `curl http://localhost:26657/status` there are 2 errors
curl: (1) Received HTTP/0.9 when not allowed
 or
curl: (56) Recv failure: Connexion ré-initialisée par le correspondant

my version is v0.16.4

**Comment by andy108369** [comment] 2022-09-11 20:38
What doc have you been following to install akash-node?

Please show me the output for:

```
ss -tulpan | grep -E "akash|2665"
```

(You can use "netstat" instead of "ss")

**Comment by camzilla1050** [comment] 2022-09-11 20:47
I followed - Node CLI Build -  https://docs.akash.network/akash-nodes/run-an-akash-node
`ss -tulpan | grep -E "akash|2665"`

![Capture d’écran du 2022-09-11 22-45-48](https://user-images.githubusercontent.com/10384623/189548198-8a7f89c1-c376-49ea-9740-f69dd63c3f6e.png)

**Comment by camzilla1050** [comment] 2022-09-11 21:11
Seems something goes wrong with http version
`curl http://localhost:26657/status --verbose --http1.1`

*   Trying ::1:26657...
sep 11 22:* Connected to localhost (::1) port 26657 (#0)
sep 11 22:> GET /status HTTP/1.1
sep 11 22:> Host: localhost:26657
sep 11 22:> User-Agent: curl/7.74.0
sep 11 22:> Accept: */*
sep 11 22:> 
sep 11 22:* Received HTTP/0.9 when not allowed
sep 11 22:
sep 11 22:* Closing connection 0
sep 11 22:curl: (1) Received HTTP/0.9 when not allowed

**Comment by andy108369** [comment] 2022-09-11 22:00
Try "curl --http0.9 http://localhost:26657/status"
And "curl --version"

**Comment by camzilla1050** [comment] 2022-09-12 14:51
`curl --version`
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

`curl -4 --http0.9 https://127.0.0.1:26657/status`
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by andy108369** [comment] 2022-09-12 15:49
And for the 2nd command?

**Comment by camzilla1050** [comment] 2022-09-12 16:13
sorry, strangre things output
`curl --http0.9 http://localhost:26657/status`
"
curl: (56) Recv failure: Connexion ré-initialisée par le correspondant
 ����v*�S{\��6ׯ�Q�>�8�i�❜W


`curl -4 --http0.9 http://127.0.0.1:26657/status`
curl: (56) Recv failure: Connexion ré-initialisée par le correspondant

**Comment by andy108369** [comment] 2022-09-12 16:33
Please:
```
journalctl --no-pager -u akash-node.service -n100
```

**Comment by camzilla1050** [comment] 2022-09-12 16:49
`journalctl --no-pager -u akash-node.service -n100`

![Capture d’écran du 2022-09-12 18-48-07](https://user-images.githubusercontent.com/10384623/189711053-4d8b9ddb-1489-4fa0-8a13-03aa39a8dedd.png)

**Comment by andy108369** [comment] 2022-09-12 16:55
ok, the issue is clear, your node is set to `cronosmainnet_25-1` instead of `akashnet-2` for some strange reason :shrug: 

![image](https://user-images.githubusercontent.com/107317698/189712213-41451e47-2323-4bdb-83ad-686606c3b796.png)

**Comment by andy108369** [comment] 2022-09-12 17:00
Some peers running `cronosmainnet_25-1` are trying to hit your akash node, that alone is not an issue for you.
From the logs, it can be seen your akash node seem to be okay, is in sync and is at `height=7593858` as of right now.

The issue must be something else..

Are you able to share your terminal session?
There is a neat tool called tmate, you can install it https://tmate.io and then just run `tmate -F` from your terminal where I will be able to type commands to troubleshoot the issue and you are able to see what's happening on the screen directly. The session persists until I exit it.

**Comment by camzilla1050** [comment] 2022-09-12 17:09
yop i reconnected to network changing "persistent_peers" in config.toml. 

Now 

journalctl --no-pager -u akash-node.service -n100´

![Capture d’écran du 2022-09-12 19-04-47](https://user-images.githubusercontent.com/10384623/189714380-cbc98895-8326-4262-ad6f-c69b73e03955.png)

**Comment by andy108369** [comment] 2022-09-12 19:16
> I followed - Node CLI Build - https://docs.akash.network/akash-nodes/run-an-akash-node

I've just tried deploying the Akash Node following [this](https://docs.akash.network/akash-nodes/run-an-akash-node) procedure, everything worked fine for me:

```
root@ssh-6466f59dfd-9wt6n:~# curl http://127.0.0.1:26657/status
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "0"
      },
      "id": "d03f576ea3265a6af0d360ab2f5471a363cf2f0e",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "akashnet-2",
      "version": "0.34.19",
      "channels": "40202122233038606100",
      "moniker": "mreaster",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "B2777C911E656DA6C5BC753398674A32860FBB97B690D403FECDE0DFE50A4833",
      "latest_app_hash": "70BB78B484272BF5FC59CE532EB000D85BA5B3A62B80136018FC64FCEFAF2DC6",
      "latest_block_height": "7586074",
      "latest_block_time": "2022-09-12T03:42:21.12162206Z",
      "earliest_block_hash": "E25CE5DD10565D6D63CDA65C8653A15F962A4D2960D5EC45D1DC0A4DE06F8EE3",
      "earliest_app_hash": "19526102DDBCE254BA71CC8E44185721D611635F638624C6F950EF31D3074E2B",
      "earliest_block_height": "5851001",
      "earliest_block_time": "2022-05-12T17:51:58.430492536Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "E1C390957B56D724CB966D69415430E7EFC274DF",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "aJL2hK38eJlxOMu36QT10rzC21OahdQJBcUGafAtt/E="
      },
      "voting_power": "0"
    }
  }
}
```

with the older curl version it is also working:

```
root@ssh-6466f59dfd-9wt6n:~# curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

root@ssh-6466f59dfd-9wt6n:~# curl http://localhost:26657/status
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "node_info": {
      "protocol_version": {
...
```

Just out of curiosity, would `curl google.com` work for you?

**Comment by camzilla1050** [comment] 2022-09-13 16:01
Tnx, I think the best is reinstall my os and follow the akash cli install tutorial again.

![Capture d’écran du 2022-09-13 17-54-11](https://user-images.githubusercontent.com/10384623/189950030-29435aa0-d93e-43cd-bcfc-48e51ec49de0.png)

Maybie i need to increase my skills with docker an kubernetes 
Tnx for your time and helping

**Comment by andy108369** [comment] 2022-09-13 16:05
What is your OS distribution?
I would suggest you go with Ubuntu 22.04 LTS

**Comment by camzilla1050** [comment] 2022-09-13 17:09
Debian GNU/Linux 11 (bullseye)

**Comment by camzilla1050** [comment] 2022-09-13 17:11
ok i will try with ubuntu

**Comment by andy108369** [comment] 2022-09-15 18:17
gonna close it, please feel free to reopen if the issue persists.

**Closed by andy108369** 2022-09-15 18:17 UTC

**Comment by camzilla1050** [comment] 2022-09-16 15:35
Tnx andy108369 , now that works fine !)
